name: PR Insight Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pr-insight:
    runs-on: ubuntu-latest
    steps:
      - uses: sanaf1333/PR-Insight-Agent@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ai_model_name: gemini-2.5-flash-lite
          docs_path: README.md
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
